### ISSUE TITLE
Add pet

### ISSUE THREAD

**Issue by birchtho** [birchtho/Huuskafi#16]

**Comment by zipperbysam** [comment]
Der Anwender möchte Haustiere zu seinem Account dazufügen, editieren oder löschen können. Ein Bild pro Tier soll in der Darstellung der Nadelposition in #24 möglich sein

**Comment by zipperbysam** [comment]
Seite 'Add_pet' generiert:
`<html><Head>Lola rennt</Head><body>Pet name</body>`
